### ISSUE TITLE
Submit score

### ISSUE THREAD

**Issue by carlosmatias** [DodgingCone/DodgingConeUnity#5]
__Athenticate user__
Fields needed:
>-Email
>-Password

__Create Model for payload__
Dates needed:
>-Uid
>-Access-Token
>-Client
>-Expiry
>-Token-Type
>-Score

__Shown  Result__
Succes or error

**Comment by lucio-martinez** [comment]
The request to upload a score is a POST to `/api/scores` with the following payload structure:

    {
      "score": {
        "score": 1
      }
    }

As previously mentioned, the request also must have five headers:
 - Uid
 - Access-Token
 - Client
 - Expiry
 - Token-Type
